.travis.yml
deepreg/config/mr_ddf.yaml
deepreg/config/mr_us_cond.yaml
deepreg/config/mr_us_dvf.yaml
deepreg/config/paired_labeled_ddf.yaml
deepreg/config/parser.py
deepreg/config/unpaired_labeled_ddf.yaml
deepreg/data/load.py
deepreg/data/loader.py
deepreg/data/nifti/nifti_paired_labeled_loader.py
deepreg/data/nifti/nifti_unpaired_loader.py
deepreg/model/network/build.py
deepreg/model/network/cond.py
deepreg/model/network/ddf.py
deepreg/model/network/dvf.py
deepreg/model/network/network.py
deepreg/model/network/util.py
deepreg/model/optimizer.py
deepreg/predict.py
deepreg/train.py
test/output/test_train_predict.py

Refactor the code for later supporting unlabeled data.

5 data loader support

---

deepreg/gen_tfrecord.py
deepreg/predict.py
deepreg/train.py
setup.py

- Doesn't break tests
- Makes the linter a lot happier :)

Issue #48: modified click arguments to standard argparse

---

.pylintrc
deepreg/model/layer_util.py

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #45 
This issue pre-linted layer-utils prior to testing. Additionally, a pylint file has been added for linting standards to the code. This should help enforce a more consistent coding style in contributions.
Docs change, no tests.

45 pre linting

---

README.md
docs/CONTRIBUTING.md
docs/ISSUE_TEMPLATE.md

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #52 
This issue fixed on fixing a number of small problems in the docs, especially in README:
- The link to contributions doc was broken 
- The instructions for using the train, predict and gen_tfrecord were simplified in the README
- Created small guideline to commit style with examples so that repo history moves towards more consistent.
- There was a small typo in the issue template with one of the headers.
- Removed requirements.txt from readme as this file no longer exists in 
Docs update, no tests

52 update readme usage style

---

README.md
deepreg/predict.py
deepreg/train.py

Argparse options were broken after updating from click. Have removed invalid ones, and updated others to retain all functionality (such as default info).
Fixes #53.
Once in the repo, type `predict --help` and `train --help` to view the changes, and ensure that all options are run correctly.

Issue #53: Updated train/predict argparse issues

---

tutorials/setup.md

Added .md file with instructions on how to install DeepReg both for normal usage and development. Updated the wiki with pointers to master branch.
Fixes #34 
N/A

Issue #34: added setup tutorial with instructions on installing DeepReg

---

README.md
tutorials/registration.md
tutorials/sampling.md

Doc changes for data sampling and readme.
doc
n/a
n/a

65 doc data sampling

---

README.md
tutorials/predefined_loader.md
tutorials/predefined_loader_h5.md
tutorials/predefined_loader_nifti.md
tutorials/sampling.md

Adding new tutorial on data loaders
Fixes # (issue)
Documentation update
n/a
**Test Configuration**:
* Firmware version:
* Hardware:

37 doc predefined loader

---

.isort.cfg
deepreg/dataset/util.py
setup.py
test/unit/test_dataset_util.py

- Added unit tests for deepreg/dataset/utils
- Linting the module deepreg/dataset/utils
- Updated requirements in setup and isort
Fixes #96

96 test dataset utils

---

deepreg/model/layer_util.py
test/unit/test_layer_util.py

Add documentation to functions in layer_util.go
Add corresponding tests
Fixes #55

55 layer util

---

demos/paired_ct_lung/README.md
demos/paired_ct_lung/demo_data.py
demos/paired_ct_lung/demo_predict.py
demos/paired_ct_lung/demo_train.py
demos/paired_ct_lung/paired_ct_lung.yaml
demos/unpaired_ct_lung/README.md
demos/unpaired_ct_lung/demo_data.py
demos/unpaired_ct_lung/demo_predict.py
demos/unpaired_ct_lung/demo_train.py
demos/unpaired_ct_lung/unpaired_ct_lung.yaml

Added the ct lung demo for the paired and unpaired cases
Fixes #11 
Tested all scripts by running them (no new unit tests were added)

#11 ct lung demo

---

deepreg/model/optimizer.py
test/unit/test_model_optimizer.py

Lint of get_optimizer function, unit tests to assert correct class of optimizers returned with the given configs.
Fixes #93 

93 test model optimizer

---

.travis.yml
deepreg/config/mr_us_cond.yaml
deepreg/config/mr_us_dvf.yaml
deepreg/config/paired_labeled_global_ddf.yaml
deepreg/config/test/ddf.yaml
deepreg/config/unpaired_labeled_ddf.yaml
deepreg/model/network/cond.py
deepreg/model/network/ddf.py
deepreg/model/network/dvf.py
deepreg/model/network/util.py
demos/paired_ct_lung/README.md
demos/unpaired_ct_lung/README.md

SImplify the backbone part in the config.
Fixes #109

109 docs configuration

---

docs/CONTRIBUTING.md
docs/_coverpage.md
docs/doc_configuration.md
docs/doc_data_loader.md
docs/quick_start.md

Proofread the changes only. 
Doc update

115 doc review

---

deepreg/config/test/ddf.yaml
deepreg/config/test/dvf.yaml
deepreg/model/network/build.py
deepreg/model/network/ddf.py
deepreg/model/network/dvf.py
deepreg/predict.py
test/output/test_dvf.py

- Support DVF model based on DDF model.
- Added DVF in prediction output.
Fixes #120

Issue #120 fix dvf model, save dvf in predict, and add test

---

demos/paired_ct_lung/README.md
demos/unpaired_ct_lung/README.md

Updated the lung ct demos
Fixes #132

132 lung ct demo update

---

docs/quick_start.md

An urgent update on the quick start - missing tensorflow lib
Doc update

Issue #134 [skip travis] hot fix for quick start

---

docs/doc_data_loader.md
docs/experiment.md

Add the tutorial for experiment design
doc update.

Issue #41 [ci skip] experiment desgin doc added

---

docs/_sidebar.md
docs/quick_start.md
docs/tutorial_demo.md

doc updated to add windows setup info - win+gpu will not be supported

Issue #138 [ci skip] adding setup info for windows

---

docs/CONTRIBUTING.md
docs/quick_start.md

Fix some typos in the doc.
Fixes #138

138 win setup

---

docs/doc_data_loader.md
docs/tutorial/demo.md
docs/tutorial/experiment.md
docs/tutorial_experiment.md
docs/tutorial_registration.md

text update and remove the tutorial folder for a flat doc structure
Fixes #41 
doc update

Issue #41 [ci skip] text update and clean-up file/names

---

deepreg/model/network/util.py

Using the weight specified in the config file for the label loss
Fixes # (153)
I'm running the demo under branch 24-mr-brain

Issue #153

---

docs/CODE_OF_CONDUCT.md

update contact details in coc.
doc update

Issue #139 [ci skip] CoC contact updated

---

test/unit/test_h5_loader.py
test/unit/test_nifti_loader.py

test for nifti file loader added
Fixes #125 
ran tests locally to check

Issue #125: add test for nifti file loader

---

deepreg/dataset/loader/grouped_loader.py
deepreg/dataset/loader/interface.py
deepreg/dataset/util.py
docs/CONTRIBUTING.md

- Add docstrings to grouped_loader
- SImplify the code a little.
Fixes #157

157 docs additions to the docstrings for loaders

---

deepreg/dataset/loader/unpaired_loader.py
test/unit/test_unpaired_data_loader.py

Add docstrings un the unpaired_data_loader class and define the unit tests for the class
Fixes #127 #159 
pytest test_unpaired_data_loader.py

Issue #127 Unpaired data loader tests

---

deepreg/model/layer_util.py
setup.py

Allow using DeepReg with tf2.0.0
Fixes #179

179 docs support cuda 100 with tf200

---

deepreg/model/layer_util.py
setup.py

Reverts DeepRegNet/DeepReg#180

Revert "179 docs support cuda 100 with tf200"

---

test/unit/test_model_optimizer.py

Issue #184: change instance in optimizer test

---

deepreg/model/layer.py
test/unit/test_layer.py

This PR includes:
- Docstring updates in the layer.py
- Minor bug fixed in layer.py when building Deconv3dBlock class
- Unit testing for the file layer.py
Fixes # (92)
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
This can be tested by running `pytest test_layer.py` in ~/tests/unit/
This can be tested by running `pytest test_layer.py` in ~/tests/unit/

92 test layer

---

deepreg/model/optimizer.py
deepreg/predict.py
deepreg/train.py
docs/CONTRIBUTING.md
test/output/test_unpaired_labeled.py
test/unit/test_model_optimizer.py
test/unit/test_train.py

Issue #170: refactor train.py

---

deepreg/config/unpaired_labeled_affine.yaml
deepreg/model/backbone/global_net.py
deepreg/model/network/affine.py
deepreg/model/network/build.py
deepreg/model/network/util.py
test/unit/test_backbone.py
test/unit/test_network_affine.py
test/unit/test_network_cond.py
test/unit/test_network_ddf_dvf.py

I added the affine network option (fixes #59) and write some tests for each network options, i.e., affine, dvf/ddf and conditional networks ( #128). 
Please describe the tests that you ran to verify your changes. Provide instructions so
we can reproduce. Please also list any relevant details for your test configuration If
there are no tests written, flag with label so we can help generate some tests before
merge.

59 affine transform

---

deepreg/dataset/loader/paired_loader.py
test/unit/test_paired_loader.py

unit test file for paired loader added: /test/unit/test_paired_loader.py
comments amended for clarity in: /deepreg/dataset/loader/paired_loader.py
Fixes # 126
unit test
- unit test ran successfully on local machine.
**Test Configuration**:
- DeepReg CPU conda env
- Windows 10
- main branch from 14 / 07 / 2020
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes

126 dataset paired loader

---

deepreg/dataset/preprocess.py
deepreg/model/loss/deform.py
deepreg/model/loss/image.py
deepreg/model/loss/label.py

Add docstrings for functions in loss module.
Also for #107 and #108 
Fixes #152 
@QianyeYang, I added a bit more details on the functions in deform, especially about the tensor shapes. Compared to your branch, you can feel free to replace the whole file once this PR is merged ;) I adopted your changes in #194

Issue #152: add docstrings for functions in loss module

---

deepreg/predict.py

As explained in the issue, it's bug due to typo.
Fixes #214

Issue #214: fix image_dir path when labeled

---

deepreg/dataset/load.py
test/unit/test_dataset_load.py

Added an error message to verify the data paths are all directories and exist.
Also added tests to cover all functions in `deepreg/dataset/load.py`
Fixes #216 #232

216 path in config

---

demos/paired_ct_lung/README.md
demos/paired_ct_lung/demo_data.py
demos/paired_ct_lung/demo_predict.py
demos/unpaired_ct_lung/README.md
demos/unpaired_ct_lung/demo_data.py
demos/unpaired_ct_lung/demo_predict.py
demos/unpaired_ct_lung/unpaired_ct_lung.yaml

Made some minor changes to ct lung demos which allows them to work with current deepreg version
Fixes #221 
Fixes #217 
ran demos locally

221 ct lung demos update

---

README.md
demos/classical_ct_headandneck_affine/README.md
demos/classical_mr_prostate_nonrigid/README.md
demos/paired_ct_lung/README.md
demos/unpaired_ct_lung/README.md
demos/unpaired_us_prostate_cv/README.md
docs/CONTRIBUTING.md
docs/home.md
docs/quick_start.md
docs/tutorial_demo.md
docs/tutorial_experiment.md
docs/tutorial_registration.md

This is a doc update address several issues tagged with proofread - see individual commits for details
fix issues #211 #222 #225 
doc update

225 doc update

---

README.md

Badge links were incorrect from the migration of old repo into the new one.
Fixes #210.

210 Update badge links for Travis

---

demos/paired_ct_lung/README.md
demos/paired_ct_lung/demo_predict.py
demos/unpaired_ct_lung/README.md
demos/unpaired_ct_lung/demo_data.py
demos/unpaired_ct_lung/demo_predict.py

Both ct_lung demo_predict scripts updated to work with new predict function.
Fixes #244 
Tested both demos by running locally. Additionally, the predict script was tested in the notebook saved in 196-yh

244 update ct lung demos

---

docs/CONTRIBUTING.md

Add detailed guidelines for testing with example code/test.
Fixes #259

Issue #259: add guidelines for testing

---

docs/Intro_to_Medical_Image_Registration.ipynb

Switch to tag `miccai2020-challenge`
Fixes #270

Issue #270: fix deepreg issue in notebook [skip ci]

---

deepreg/dataset/util.py
deepreg/predict.py
deepreg/util.py
docs/doc_configuration.md
test/unit/test_dataset_util.py
test/unit/test_predict.py
test/unit/test_train.py
test/unit/test_util.py
test/unit/test_warp.py

- remove redundant outputs
- make both nifti and png saving configurable
- updated the docs
Fixes #255

255 improve the predict output

---

README.md
docs/CONTRIBUTING.md
docs/_sidebar.md
docs/doc_demo_requirement.md
docs/home.md
docs/quick_start.md

Documentation update.
1 - fix links on readme;
2 - restructured the readme/homepage to avoid repetitions
3 - moved the demo requirement to doc
Fixes #252 #269 
doc update only

252 demo doc update

---

demos/unpaired_us_prostate_cv/README.md
docs/_sidebar.md
docs/doc_command.md
docs/quick_start.md
docs/tutorial_experiment.md

Fixes #294 
doc proofread updates

Issue #294 [ci skip] links fixed and deepreg_ added

---

deepreg/dataset/loader/interface.py
deepreg/model/loss/image.py
test/unit/test_loss_image.py

Add more comments to explain the calculation in lncc loss
Actually, this is squared local normalized cross correlation
Fixes #273 #234

Issue #273: add comments for lncc

---

docs/doc_add_network.md

issue #39: add network documentation

---

demos/paired_ct_lung/README.md
demos/paired_ct_lung/demo_predict.py
demos/paired_ct_lung/demo_train.py
demos/paired_ct_lung/paired_ct_lung_train.yaml
demos/paired_mrus_brain/README.md
demos/paired_mrus_brain/demo_predict.py
demos/paired_mrus_brain/demo_train.py
demos/paired_mrus_brain/paired_mrus_brain_train.yaml
demos/unpaired_ct_lung/README.md
demos/unpaired_ct_lung/demo_predict.py
demos/unpaired_ct_lung/demo_train.py
demos/unpaired_ct_lung/unpaired_ct_lung_train.yaml

Separate config files added for demos
Fixes #299

Issue #299: use separate config files for demos

---

demos/unpaired_mr_brain/demo_data.py

Refactoring of some parts of the code for demo to comply with general rules. Exact changes are:
- Move files from google drive to github and update the code accordingly 
- Use get_file from keras instead of system calls.
Fixes # (297)

Demo review and styling #297 

---

docs/joss_paper/paper.md

Fixes image links in joss paper

Issue #289: fix image links in joss paper

---

docs/source/tutorial/custom_network.md
docs/source/tutorial/registration.md

This is a continuation of #323. All the tutorials have now been reviewed. 
Partially addresses #322 

322 s sd docs review 2

---

demos/paired_mrus_prostate/README.md
docs/source/contributing/code.md
docs/source/contributing/demo.md
docs/source/contributing/docs.md
docs/source/contributing/pull_request.rst
docs/source/contributing/setup.md
docs/source/contributing/test.md
docs/source/demo/introduction.rst
docs/source/demo/readme_template.md
docs/source/docs/cli.md
docs/source/docs/configuration.md
docs/source/docs/dataset_loader.md
docs/source/docs/experimental.rst
docs/source/getting_started/quick_start.md
docs/source/introduction.rst
docs/source/tutorial/cross_val.md
docs/source/tutorial/custom.rst
docs/source/tutorial/custom_network.md
docs/source/tutorial/registration.md

325 improve contributing pages

---

demos/unpaired_ct_lung/README.md

change.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so
we can reproduce. Please also list any relevant details for your test configuration If
there are no tests written, flag with label so we can help generate some tests before
merge.
**Test Configuration**:
- Firmware version:
- Hardware:

Issue #321, fix 404 links and adjust readme order

---

demos/classical_mr_prostate_nonrigid/README.md
demos/classical_mr_prostate_nonrigid/demo_register.py

Review of the classical_mr_prostate_nonrigid demo
I had no problems running the demo. Readme file and results are clear. I just corrected minor typos.

classical_mr_prostate_nonrigid demo

---

demos/unpaired_us_prostate_cv/README.md
docs/source/demo/readme_template.md

Update unpaired us prostate readme
- doc change

Issue #321: adapt unpaired us prostate readme to template

---

demos/paired_mrus_brain/README.md
demos/paired_mrus_brain/demo_data.py
demos/paired_mrus_brain/demo_predict.py
demos/paired_mrus_brain/demo_train.py
demos/paired_mrus_brain/paired_mrus_brain.yaml
demos/unpaired_ct_lung/demo_predict.py
test/unit/test_preprocess.py

Review of the paired_mrus_brain demo.
I corrected typos and modified description of the demo. I did not have any problem running the demo.
New edits:
Both suggestions (see below) incorporated:
- typo in dataset corrected
- message displayed at the end of predict to point the user to the folder containing the generated and original images
- I don't know if it worth mentioning this but there is a typo for the dataset name. All the folder created refers to "respect-dataset" instead of "resect-dataset". I didn't correct the typo to avoid any confusion because the directory from which the data is downloaded (https://github.com/ucl-candi/dataset_respect/archive/master.zip) have the same typo.
- The demo only outputs a plot is in 2D and it is difficult to visualize/assess the registration …

Issue #321- Paired mr us brain demo

---

demos/unpaired_ct_abdomen/README.md

Review for unpaired abdominal CT registration demo.
The demo_data.py, deepreg_train and deepreg_predict work fine.
The readme.md has been modified including fixing the typos, adjusting the orders.

#321 demo review for unpaired abdominal CT registration demo

---

demos/grouped_mask_prostate_longitudinal/README.md

Review for grouped_mask_prostate_longitudinal registration demo.
The demo_data.py, deepreg_train and deepreg_predict work fine.
The readme.md has been modified including fixing the typos, adjusting the orders.

#321 demo review for grouped_mask_prostate_longitudinal

---

demos/unpaired_ct_lung/README.md

change.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so
we can reproduce. Please also list any relevant details for your test configuration If
there are no tests written, flag with label so we can help generate some tests before
merge.
**Test Configuration**:
- Firmware version:
- Hardware:

Issue #321, update readme, restore link

---

docs/source/docs/exp_label_sampling.md
docs/source/docs/experimental.rst

Review of `experimental.rst` and `exp_label_sampling.md`. 
Partially fixes Issue #322 
@ebonmati @agrimwood I added a couple of comments into `exp_label_sampling.md` and would love your feedback!

Issue #322: reviewed experimental features documentation

---

deepreg/config/unpaired_labeled_affine.yaml
deepreg/config/unpaired_labeled_ddf.yaml
docs/source/contributing/build.md
docs/source/contributing/demo.md
docs/source/contributing/guide.md
docs/source/contributing/setup.md
docs/source/demo/introduction.rst
docs/source/demo/readme_template.md
docs/source/docs/cli.md
docs/source/docs/configuration.md
docs/source/docs/dataset_loader.md
docs/source/docs/exp_label_sampling.md
docs/source/docs/experimental.rst
docs/source/getting_started/install.rst
docs/source/getting_started/quick_start.md
docs/source/introduction.rst
docs/source/tutorial/cross_val.md

overall proofread of the entire documentation - 0
Fixes #322 
doc update

322 proofread-0

---

docs/source/docs/cli.md

Issue #242: add description of output files for cli tools

---

demos/unpaired_mr_brain/README.md
demos/unpaired_mr_brain/demo_predict.py

Issue #321: unpaired mri brain demo review

---

demos/classical_ct_headneck_affine/README.md
demos/classical_mr_prostate_nonrigid/README.md
demos/grouped_mask_prostate_longitudinal/README.md
demos/grouped_mr_heart/README.md
demos/paired_ct_lung/README.md
demos/paired_mrus_brain/README.md
demos/paired_mrus_prostate/README.md
demos/unpaired_ct_abdomen/README.md
demos/unpaired_ct_lung/README.md
demos/unpaired_ct_lung/demo_data.py
demos/unpaired_mr_brain/README.md
demos/unpaired_mr_brain/demo_train.py
demos/unpaired_us_prostate_cv/README.md
demos/unpaired_us_prostate_cv/demo_data.py
docs/source/demo/introduction.rst
docs/source/demo/readme_template.md
docs/source/introduction.rst

- Demo doc review
- Demo readme review
- Make a consistent style for the demo readme and doc
- Add pretrained model to unpaired-us 
Fixes #321

321 demo review 0

---

deepreg/dataset/loader/grouped_loader.py
deepreg/dataset/loader/h5_loader.py
deepreg/dataset/loader/interface.py
deepreg/dataset/loader/nifti_loader.py
deepreg/dataset/loader/paired_loader.py
deepreg/dataset/loader/unpaired_loader.py
docs/source/contributing/code.md
docs/source/contributing/docs.md
docs/source/contributing/pull_request.rst
docs/source/contributing/setup.md
docs/source/contributing/test.md
docs/source/demo/introduction.rst
docs/source/docs/cli.md
docs/source/docs/dataset_loader.md
docs/source/docs/exp_label_sampling.md
docs/source/docs/experimental.rst
docs/source/introduction.rst
docs/source/tutorial/cross_val.md
docs/source/tutorial/custom.rst

Solved minor errors during proofreading.
Fixes #362
apply_

362 general proofreading

---

.github/workflows/pre-commit.yml

Use github action so that in case of files not being correctly formatted, a commit will be added automatically.
Fixes #365
apply_

Issue #365: add pre-commit action

---

demos/classical_ct_headneck_affine/README.md
demos/grouped_mask_prostate_longitudinal/README.md
demos/grouped_mr_heart/README.md
demos/paired_ct_lung/README.md
demos/paired_ct_lung/demo_predict.py
demos/paired_mrus_brain/README.md
demos/paired_mrus_prostate/README.md
demos/unpaired_ct_abdomen/README.md
demos/unpaired_ct_lung/README.md
demos/unpaired_ct_lung/demo_predict.py
demos/unpaired_mr_brain/README.md
demos/unpaired_mr_brain/demo_predict.py
demos/unpaired_us_prostate_cv/README.md
docs/source/demo/introduction.rst
docs/source/getting_started/install.rst
docs/source/getting_started/quick_start.md

General review of the demo documentation.
Fixes #370 
apply_

370 docu demo review

---

test/unit/test_backbone.py
test/unit/test_layer.py
test/unit/test_network_util.py

Avoid instantiating objects just to check their classes. This would simplify the readability of the unit tests.
Fixes #376 
- [X ] I have
- [ X] My commits' message styles matches
- [ X] I have added tests that prove my fix is effective or that my feature works

Simplify type check in tests

---

README.md
deepreg/model/backbone/u_net.py
deepreg/model/layer.py
deepreg/model/layer_util.py
demos/classical_ct_headneck_affine/README.md
demos/classical_mr_prostate_nonrigid/README.md
demos/grouped_mask_prostate_longitudinal/README.md
demos/grouped_mr_heart/README.md
demos/paired_ct_lung/README.md
demos/paired_mrus_brain/README.md
demos/paired_mrus_prostate/README.md
demos/unpaired_ct_abdomen/README.md
demos/unpaired_ct_lung/README.md
demos/unpaired_mr_brain/README.md
demos/unpaired_us_prostate_cv/README.md
docs/Intro_to_Medical_Image_Registration.ipynb
docs/source/contributing/demo.md
docs/source/contributing/guide.md
docs/source/contributing/issue.md
docs/source/contributing/test.md
docs/source/demo/readme_template.md
docs/source/docs/configuration.md
docs/source/docs/dataset_loader.md
docs/source/index.rst
docs/source/introduction.rst

Fix master -> main related errors
This is a hotfix, so merge to master directly
Fixes #383 #371
apply_

383 logo on readme is not displayed

---

docs/source/contributing/build.md
docs/source/contributing/pull_request.rst
docs/source/contributing/setup.md
docs/source/demo/introduction.rst
docs/source/getting_started/install.rst

Doc change to clarify the demo and quick start will require additional setting to run
Fixes #<issue_number>

382 pypi clarification

---

docs/joss_paper/paper.bib

Issue #399: add missing DOIs

---

README.md
docs/source/getting_started/quick_start.md

Hotfix for broken link in `quick_start.md` to redirect to the install page, whereas previously it redirected to the 404 page.
Fixes #404 
apply_

Issue #404: Updated install path from quick start page.

---

.pre-commit-config.yaml
.prettierrc

Updated the hook versions in config files and reformated all files using `pre-commit run --all-files`.
Fixes #418
apply_

418 update pre commit hook

---

docs/joss_paper/paper.md

Update Eugenio's affiliations and add city, country to all affiliations.
Fixes #405
apply_

Issue #405: update Eugenio affiliations

---

docs/joss_paper/paper.bib

Add DOI for two MICCAI papers.
Fixes #440
apply_

Issue #440: add missing DOIs for two papers

---

deepreg/dataset/loader/util.py
deepreg/dataset/preprocess.py
deepreg/model/loss/image.py
deepreg/model/loss/label.py
deepreg/predict.py
deepreg/train.py
deepreg/util.py
docs/source/docs/cli.md
test/unit/test_dataset_loader_util.py
test/unit/test_loss_image.py
test/unit/test_loss_label.py
test/unit/test_preprocess.py
test/unit/util.py

442 test bug in is equal

---

docs/source/tutorial/run_cluster.md

413 cluster script

---

.github/ISSUE_TEMPLATE/01_bug_report.md
.github/PULL_REQUEST_TEMPLATE.md

Issue #453: add instruction to get commit hash

---

Dockerfile

Issue #458: remove checkout from docker file

---

deepreg/model/loss/image.py
test/unit/test_loss_image.py

I have added a kernel size and a kernel type option for LNCC image similarity loss. Hence, I've added the corresponding unit tests and updated the docstring.
Fixes #215 
apply_

215 loss parameters

---

deepreg/model/loss/label.py

Update the docstring regarding the usage of tf.nn.conv3d in separable_filter3d
Fixes #463
apply_

Issue #463: update separable_filter3d docstring regarding tf.nn.conv3d

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

Add changelog and update the PR template.
Fixes #462
apply_

462 add changelog

---

README.md

Modified README to add JOSS badges and MEC information.
Fixes #427 
Fixes #447 
apply_

427 and 447 readme updates

---

.github/stale.yml

Issue #461: add stale config for Stale robot

---

CHANGELOG.md
docs/source/contributing/setup.md
docs/source/contributing/test.md
docs/source/getting_started/install.rst
test/unit/util.py

Update documentation regarding installation and contributing (pre-commit setup / testing).
Fixes #416 #450 #471 
apply_
e.g. `Issue #<issue number>: …

416 450 471 update documentation

---

requirements.txt

This is urgent as it's now blocking all other PRs.
Fixes #492
apply_
[change log …

Issue #492: update h5py version requirement

---

CHANGELOG.md
README.md
docs/source/contributing/docs.md
docs/source/contributing/setup.md
docs/source/contributing/test.md

Issue #491: migrate travis ci from org to com

---

.travis.yml
CHANGELOG.md
deepreg/predict.py

Fixes #482
Tested with
```bash
deepreg_train --gpu "" --config_path config/unpaired_labeled_ddf.yaml --log_dir test
deepreg_predict --gpu "" --ckpt_path logs/test/save/weights-epoch2.ckpt --mode test -b 5
```
apply_
[our requested …

482 predict error with batch size

---

.travis.yml
CHANGELOG.md
demos/grouped_mask_prostate_longitudinal/demo_predict.py
demos/grouped_mr_heart/demo_predict.py
demos/paired_ct_lung/demo_predict.py
demos/paired_mrus_brain/demo_predict.py
demos/paired_mrus_prostate/demo_predict.py
demos/unpaired_ct_abdomen/demo_predict.py
demos/unpaired_ct_lung/demo_predict.py
demos/unpaired_mr_brain/demo_predict.py
demos/unpaired_us_prostate_cv/demo_predict.py
test/demo/test_demos.py

Issue #489: test demos depending on job type and commit msg test-demo

---

CHANGELOG.md
deepreg/dataset/loader/h5_loader.py
deepreg/dataset/loader/nifti_loader.py
test/unit/test_h5_loader.py
test/unit/test_nifti_loader.py

Issue #481: check dataset is not empty for h5 and nifti

---

CHANGELOG.md
README.md
docs/source/introduction.rst
setup.py

Issue #499: update docs regarding release v0.1.0

---

setup.py

Updated pypi release tags so that builds can be correctly uploaded.
Fixes #505 
apply_
[change log …

Issue #505: Updated to correct stable tag for PyPI releases

---

deepreg/dataset/loader/grouped_loader.py
deepreg/dataset/loader/h5_loader.py
deepreg/dataset/loader/interface.py
deepreg/dataset/loader/nifti_loader.py
deepreg/dataset/loader/paired_loader.py
deepreg/dataset/loader/unpaired_loader.py
deepreg/dataset/loader/util.py
deepreg/dataset/preprocess.py
deepreg/model/backbone/global_net.py
deepreg/model/backbone/local_net.py
deepreg/parser.py
deepreg/predict.py
deepreg/train.py
deepreg/util.py
deepreg/vis.py
deepreg/warp.py

Sentences were observed running into each other due to lack of line breaks.
Changes in this PR modify code comments to remove linebreaks and improve readability in RTD.
Fixes #394 
apply_
[our requested …

Issue #394: Add punctuation and alter linebreaks to improve docstring readability

---

CHANGELOG.md
README.md

* Update logo from beta
* Add pypi badge
* Update contributing with extra information, link to CoC
* Add citation (plain text and bibtex version)
Fixes #502 
apply_
[our requested structure](https://deepreg.readthedocs.io/en/latest/contributing/commit …

Issue #502: Post-release / post-JOSS README.md update

---

CHANGELOG.md
demos/unpaired_mr_brain/demo_data.py

I changed the location of data used in unpaired_mr_brain demo and updated  demo_data.py accordingly
Fixes #528 
apply_
e.g. `Issue #<issue number>: detailed …

528 path mrbrain

---

.github/workflows/python-publish.yml
setup.py

This GitHub workflow *should* be something we can trigger manually from the Actions tab (when this has been merged) to stage, build and upload the released package.
Before each release, we will need to ensure that setup.py has been version bumped so as to not try and re-upload the same version of the package twice (pypi won't allow that).
Once this is confirmed working, we can update the release guidelines and close #408.
apply_
[installed …

Issue #408: Add checkout, build and release workflow

---

CHANGELOG.md
deepreg/dataset/loader/interface.py
deepreg/dataset/util.py
test/unit/test_dataset_util.py
test/unit/test_interface.py

change.
Fixes #531 
apply_
[our requested …

Removed references to "first" argument in data loader index generators.

---

docs/source/tutorial/registration.md

Modified tutorial text for clarification in: 1) intensity based losses and 2) deformation losses
Fixes #496 
apply_
e.g. `Issue #<issue number>: detailed …

496 minor typos in docs

---

.pre-commit-config.yaml
.zenodo.json
README.md

Add zenodo config regarding fixed terms like names and keywords. We will see in the next release if the config is working. I've corrected the named in v0.1.1 manually for zenodo.
Also aligned tables (everything starting from the title is aligned left, so I set them to left, which is default if not defined)
check https://github.com/DeepRegNet/DeepReg/tree/521-add-zenodo-config for the visual of readme, in `Files changed` tab it's not correctly showing before and after (the reason I didn't spot the centering)
Personally, either the badges are moved above the title DeepReg to be centered as the logo, either it's left aligned with the title ;) both fine for me.
Fixes #521
apply_
_Put an `x` in the boxes …

521 add zenodo config

---

CHANGELOG.md
README.md

Added the CMIC seminar link to the README.
Fixes #508 
apply_
[change log …

Issue #508: added CMIC seminar series link to the README

---

deepreg/__init__.py
deepreg/model/__init__.py
deepreg/model/backbone/__init__.py
deepreg/model/backbone/global_net.py
deepreg/model/backbone/local_net.py
deepreg/model/backbone/u_net.py
deepreg/predict.py
deepreg/registry.py
deepreg/train.py
test/unit/test_network_affine.py
test/unit/test_network_build.py
test/unit/test_network_cond.py
test/unit/test_network_ddf_dvf.py
test/unit/test_network_util.py
test/unit/test_registry.py

Issue #517: use decorator to register built-in classes

---

CHANGELOG.md
README.md

Issue #573: add two badges

---

.github/workflows/python-unit-test.yml
deepreg/model/layer.py
test/unit/test_layer.py

Simplify the test cases and reduce unit test time
Fixes #580
[change log …

580 unit test in ci became slow

---

demos/grouped_mask_prostate_longitudinal/demo_data.py
demos/grouped_mask_prostate_longitudinal/demo_predict.py
demos/grouped_mask_prostate_longitudinal/demo_train.py
demos/grouped_mask_prostate_longitudinal/grouped_mask_prostate_longitudinal.yaml

The grouped_mask_logitudinal_prostate demo has been updated
- 10x longer training 
- smaller weights for regularisation
Fixes #570  …

570 demo grouped masks

---

CHANGELOG.md
demos/unpaired_us_prostate_cv/demo_data.py
demos/unpaired_us_prostate_cv/demo_predict.py
demos/unpaired_us_prostate_cv/unpaired_us_prostate_cv.yaml

unpaired_us_prostate_cv demo config updated with new pretrained model uploaded in the zoo
Fixes #562 
e.g. `Issue #<issue number>: …

562 demo unpaired us

---

CHANGELOG.md
demos/grouped_mr_heart/demo_data.py
demos/grouped_mr_heart/demo_predict.py
demos/grouped_mr_heart/demo_train.py
demos/grouped_mr_heart/grouped_mr_heart.yaml

Demo config updated with new pretrained model uploaded to the zoo.
- bigger model with 32 initi_ch downloading multi-part big pretrained model
- change to mutual information
- training longer than 3/4000 does not seem improving further
- larger regularisation weight made the change difficult to spot but may still be considered plausible 
Fixes #584 
[installed pre-commit](https://deepreg.readthedocs.io/en/latest/contributing/setu …

584 demo grouped cardiac

---

CHANGELOG.md
deepreg/model/loss/image.py

Small bug fix in LNCC loss function regarding triangular kernel size
Fixes #588 …

Issue #588: corrected bug - triangular kernel size in LNCC loss function

---

CHANGELOG.md
demos/paired_ct_lung/demo_data.py
demos/paired_ct_lung/demo_predict.py
demos/paired_ct_lung/demo_train.py
demos/paired_ct_lung/paired_ct_lung.yaml

Updated demo with a new pretrained model.
- bigger model and longer training;
- smaller data size during preprocessing for demo purpose;
- stronger regularisation to avoid too large local deformation
- stronger image similarity to align foreground structures without labels such as airways/vessels
- limitation: this is a typical example that the moving image has a much smaller FOV than than of the fixed image (although arguably it may not be necessary for many clinical applications). A general strategy to deal with this probably is yet available, but tools could include overlap-invariant similarity measures, masking, inverse-consistency constraint... (another ticket) 
Fixes #575 
_Please check the boxes that apply after submitting …

575 demo paired lung

---

CHANGELOG.md
demos/unpaired_ct_lung/demo_data.py
demos/unpaired_ct_lung/demo_predict.py
demos/unpaired_ct_lung/unpaired_ct_lung.yaml

The `unpaired_ct_lung` demo is updated with a longer trained, larger sized model with some hyperparameter adjustments.
The results from the new model:
Fixes #576
[our requested …

576 unpaired lung demo update

---

.gitignore
CHANGELOG.md
config/test/ddf.yaml
config/unpaired_labeled_ddf.yaml
deepreg/dataset/__init__.py
deepreg/dataset/loader/interface.py
deepreg/dataset/preprocess.py
deepreg/model/layer_util.py
demos/classical_ct_headneck_affine/demo_register.py
demos/grouped_mask_prostate_longitudinal/grouped_mask_prostate_longitudinal.yaml
demos/grouped_mr_heart/grouped_mr_heart.yaml
demos/paired_ct_lung/paired_ct_lung.yaml
demos/paired_mrus_brain/paired_mrus_brain.yaml
demos/paired_mrus_prostate/paired_mrus_prostate.yaml
demos/unpaired_ct_abdomen/unpaired_ct_abdomen_comb.yaml
demos/unpaired_ct_abdomen/unpaired_ct_abdomen_unsup.yaml
demos/unpaired_ct_abdomen/unpaired_ct_abdomen_weakly.yaml
demos/unpaired_ct_lung/unpaired_ct_lung.yaml
demos/unpaired_mr_brain/unpaired_mr_brain.yaml
demos/unpaired_us_prostate_cv/unpaired_us_prostate_cv.yaml
test/unit/test_interface.py
test/unit/test_layer_util.py
test/unit/test_preprocess.py
test/unit/test_util.py

- change transformation to keras layer
- update config to use affine transformation by default (it is a bug to train without any da)
- refactor transformation layers to reduce redundant code
- rename some funcs to make functionalities clearer
Fixes #617
certain, run …

617 refactoring of data augmentation

---

CHANGELOG.md
README.md
docs/source/docs/cli.md

Fix dead links
Fixes #611, #515
[change log …

611 515 fix links

---

CHANGELOG.md
deepreg/dataset/loader/grouped_loader.py
deepreg/dataset/loader/h5_loader.py
deepreg/dataset/loader/nifti_loader.py
deepreg/predict.py
deepreg/warp.py
test/unit/test_layer.py
test/unit/test_warp.py

Cover or ignore some tests, so that test coverage is 100%.
Fixes #379
[change log …

379 identify all code not covered by unit test

---

demos/grouped_mask_prostate_longitudinal/README.md

Add the reference for the grouped mask prostate demo
Fixes #642 
[change log …

Issue #642 reference added for the grouped_mask_prostate demo

---

deepreg/dataset/__init__.py
deepreg/dataset/load.py
deepreg/dataset/loader/__init__.py
deepreg/dataset/loader/grouped_loader.py
deepreg/dataset/loader/h5_loader.py
deepreg/dataset/loader/nifti_loader.py
deepreg/dataset/loader/paired_loader.py
deepreg/dataset/loader/unpaired_loader.py
deepreg/registry.py
docs/source/docs/registered_classes.md
test/unit/test_dataset_load.py
test/unit/test_registry.py

Use registry for data loaders and file loaders to simplify the code
Fixes #653 …

Issue #653: use registry for data loaders

---

deepreg/config/parser.py
deepreg/dataset/load.py
deepreg/predict.py
deepreg/train.py
deepreg/util.py
test/unit/test_predict.py
test/unit/test_train.py
test/unit/test_util.py

accepting the ~/ shorthand for user home
Fixes #630 
[change log …

Issue #630 expanduser to accept ~/ shorthand

---

CHANGELOG.md
config/test/affine.yaml
config/test/ddf.yaml
config/unpaired_labeled_ddf.yaml
deepreg/config/v011.py
deepreg/model/optimizer.py
demos/grouped_mask_prostate_longitudinal/grouped_mask_prostate_longitudinal.yaml
demos/grouped_mr_heart/grouped_mr_heart.yaml
demos/paired_ct_lung/paired_ct_lung.yaml
demos/paired_mrus_brain/paired_mrus_brain.yaml
demos/paired_mrus_prostate/paired_mrus_prostate.yaml
demos/unpaired_ct_abdomen/unpaired_ct_abdomen_comb.yaml
demos/unpaired_ct_abdomen/unpaired_ct_abdomen_unsup.yaml
demos/unpaired_ct_abdomen/unpaired_ct_abdomen_weakly.yaml
demos/unpaired_ct_lung/unpaired_ct_lung.yaml
demos/unpaired_mr_brain/unpaired_mr_brain.yaml
demos/unpaired_us_prostate_cv/unpaired_us_prostate_cv.yaml
docs/source/docs/configuration.md
examples/config_custom_backbone.yaml
test/unit/test_config_parser.py
test/unit/test_config_v011.py
test/unit/test_model_optimizer.py

Support all keras optimizers and simplify optimizer configs.
Fixes #647
[change log …

647 refactor optimizer config

---

CHANGELOG.md

A cleanup for the change log for r0.1.2
Fixes #657 
[change log …

Issue #657 changelog updated for r012

---

CHANGELOG.md
README.md

Video was broken to seminar.
Fixes #658 #674
[change log …

Issue #658: modified broken seminar link

---

deepreg/model/network.py
docs/source/getting_started/install.rst

Issue #685: catch import error when plot model struct and update docs

---

CHANGELOG.md
docs/source/docs/registry.md
examples/config_custom_image_label_loss.yaml
examples/config_custom_image_loss.yaml
examples/config_custom_parameterized_image_label_loss.yaml
examples/custom_image_label_loss.py
examples/custom_image_loss.py
examples/custom_parameterized_image_label_loss.py
test/integration/test_examples.py

Issue #585: add example for custom loss

---

CHANGELOG.md
deepreg/predict.py
deepreg/train.py
deepreg/util.py
demos/grouped_mask_prostate_longitudinal/demo_predict.py
demos/grouped_mask_prostate_longitudinal/demo_train.py
demos/grouped_mr_heart/demo_predict.py
demos/grouped_mr_heart/demo_train.py
demos/paired_ct_lung/demo_predict.py
demos/paired_ct_lung/demo_train.py
demos/paired_mrus_brain/demo_predict.py
demos/paired_mrus_brain/demo_train.py
demos/paired_mrus_prostate/demo_predict.py
demos/paired_mrus_prostate/demo_train.py
demos/unpaired_ct_abdomen/demo_predict.py
demos/unpaired_ct_abdomen/demo_train.py
demos/unpaired_ct_lung/demo_predict.py
demos/unpaired_ct_lung/demo_train.py
demos/unpaired_mr_brain/demo_predict.py
demos/unpaired_mr_brain/demo_train.py
demos/unpaired_us_prostate_cv/demo_predict.py
demos/unpaired_us_prostate_cv/demo_train.py
docs/source/docs/cli.md
docs/source/getting_started/quick_start.md
test/unit/test_predict.py
test/unit/test_train.py
test/unit/test_util.py

- Rename `log_dir` to `exp_name`
- Rename `log_root` to `log_dir`
Fixes #590 …

Issue #590: rename log_dir to exp_name and log_root to log_dir

---

.pre-commit-config.yaml
CHANGELOG.md
deepreg/config/v011.py
deepreg/loss/label.py
docs/source/docs/configuration.md
test/unit/test_config_v011.py
test/unit/test_loss_label.py

Issue #632: rename neg_weight to background_weight

---

CHANGELOG.md
docs/Contributors.md
docs/source/introduction.rst

Move the contributor list to a separate page 
Fixes #705 
[change log …

705 separate contributor list

---

CHANGELOG.md
docs/source/docs/dataset_loader.md
docs/source/docs/exp_label_sampling.md

Edited the doc to clarify the use of all-zero masks for missing data, instead of the alternatives with "automated handling missing data" which may be considered error-prone without clear benefit.
Fixes #162 
[our requested …

Issue #162 clarify the use of missing labels

---

CHANGELOG.md
deepreg/loss/label.py
deepreg/model/layer.py
deepreg/model/network.py
deepreg/train.py
deepreg/util.py
test/unit/test_loss_label.py

Fixes #708
Added
- support for `update_freq`
- TRE metric when data are labeled
- stats (min/max/mean) on fixed/moving images/labels and DDF
[our requested structure](https://deepreg.readthedocs.io/en/latest/contributing/commi …

708 log more metrics in tensorboard

---

.pre-commit-config.yaml
CHANGELOG.md
config/test/grouped_mr_heart_v011.yaml
deepreg/dataset/loader/interface.py
deepreg/dataset/preprocess.py
deepreg/loss/deform.py
deepreg/loss/image.py
deepreg/loss/label.py
deepreg/model/network.py
deepreg/predict.py
deepreg/train.py
deepreg/util.py
demos/grouped_mask_prostate_longitudinal/grouped_mask_prostate_longitudinal.yaml
demos/grouped_mr_heart/grouped_mr_heart.yaml
demos/paired_ct_lung/paired_ct_lung.yaml
demos/paired_mrus_brain/paired_mrus_brain.yaml
demos/paired_mrus_prostate/paired_mrus_prostate.yaml
demos/unpaired_ct_abdomen/unpaired_ct_abdomen_comb.yaml
demos/unpaired_ct_lung/unpaired_ct_lung.yaml
demos/unpaired_mr_brain/unpaired_mr_brain.yaml
demos/unpaired_us_prostate_cv/unpaired_us_prostate_cv.yaml
docs/source/docs/cli.md
docs/source/docs/configuration.md
examples/custom_image_label_loss.py
examples/custom_parameterized_image_label_loss.py
test/unit/test_interface.py
test/unit/test_loss_deform.py
test/unit/test_loss_image.py
test/unit/test_loss_label.py
test/unit/test_network.py

The main issue that dice score > 1 because the added metrics were not normalized by the global batch size.
In this PR, we also double-checked/refactored the implementation of several loss functions and added extensive tests to verify.
Fixes #734
certain, run …

734 large dice

---

deepreg/dataset/preprocess.py
deepreg/loss/__init__.py
deepreg/loss/deform.py
deepreg/loss/image.py
deepreg/loss/kernel.py
deepreg/loss/label.py
deepreg/loss/util.py
deepreg/model/network.py
deepreg/registry.py
deepreg/util.py
docs/source/docs/registered_classes.md
examples/custom_image_label_loss.py
examples/custom_parameterized_image_label_loss.py
test/unit/test_loss_image.py
test/unit/test_loss_kernel.py
test/unit/test_loss_label.py
test/unit/test_loss_util.py
test/unit/test_registry.py

739 refactor losses

---

CHANGELOG.md
config/test/affine.yaml
config/test/ddf.yaml
config/unpaired_labeled_ddf.yaml
deepreg/dataset/loader/interface.py
deepreg/model/network.py
deepreg/predict.py
deepreg/train.py
docs/source/docs/cli.md
docs/source/docs/configuration.md

Issue #720: enable to define num_parallel_calls in config

---

docs/source/tutorial/run_cluster.md

change.
Fixes #<issue_number>
- [ v] Documentation Update (fix or improvement on the documentation)
- [v ] I have
using `pre-commit install` and formatted all changed files. If …

Issue #788: Add docs for steps to install deepreg environment in cluster

---

CHANGELOG.md
demos/unpaired_ct_abdomen/demo_predict.py
demos/unpaired_ct_abdomen/unpaired_ct_abdomen_comb.yaml
demos/unpaired_ct_abdomen/unpaired_ct_abdomen_unsup.yaml
demos/unpaired_ct_abdomen/unpaired_ct_abdomen_weakly.yaml

update the pre-trained models for the unpaired_ct_abdominal demo to the new version
Fixes #802
train & predict script and files at model zoo …

802 demo pretrained unpaired ct abd
