DeepRegNet/DeepReg

setup.py

Removed nilearn from `setup.py`. `nilearn` no longer exists in the code.
Fixes #60
I ran
- `pip install -e .`
- `pytest ./test/output`

remove nilearn

---

deepreg/model/network/util.py
test/unit/test_network_util.py

Built unit tests to check that build_backbone and build_inputs works as expected. Coverage for this submodule at 86% according to local pytest-cov report.
Fixes #95 

95 test network utils

---

deepreg/model/loss/label.py
test/unit/test_backbone.py
test/unit/test_loss_label.py

Case constants to tf.float32 to make sure using GPU `pytest test/units` can pass.
Fixes #188
On PT with GPU and locally without GPU.

188 bug pytest with gpu cant pass pytest test unit

---

demos/README.md
docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING.md
docs/_coverpage.md
docs/doc_configuration.md
docs/doc_data_loader.md
docs/index.html
docs/quick_start.md
docs/tutorial_demo.md

Links are fixed to NiftyRegNet-based, though the redirecting still works.
Fixes #169 
do update

Issue #169 [ci skip] doc links fixed

---

test/unit/test_unpaired_data_loader.py

Fixes #189
The test was due to a bug in `sample_index_generator` that different seeds give the same order of data.
So, the main objective of the test should be testing that different seeds give different orders,
which should be irrelevant to the split, "train" or "test".
Thus, I modified the test to test the collected indices are the same for the same seeds and different for different seeds.

Issue #189: fix random seed to make test deterministic

---

deepreg/model/layer_util.py
test/unit/test_layer_util.py

Reached 100% coverage for layer_utils.py and removed unreachable code block where a secondary check of image_dim took place.
Previous test_layer_utils achieved ~95% coverage - this covers all failure cases for the functions which were not previously covered.
Fixes #55 
Tested coverage with `pytest test_layer_utils.py --cov-report term-missing --cov` achieves 100%

Issue #55: Improve coverage for layer_utils.py

---

demos/unpaired_ct_lung/unpaired_ct_lung.yaml

Fix the demo config in case of unpaired, as shown here https://deepregnet.github.io/DeepReg/#/doc_data_loader?id=configuration-1, we should use `image_shape` instead of `moving_image_shape` or `fixed_image_shape` as images are not paired.

unpaired data config should only use `image_shape` [skip ci]

---

deepreg/dataset/loader/nifti_loader.py

Added support for nii files in the nifti loader. The nifti loader can now handle folders with the following cases:
- All nii.gz files
- All nii files
- Some nii and some nii.gz files
Fixes #230 
ran unit tests for nifti_loader locally and tested nifti loader with demo data from mr_us_brain demo data which has nii files.

Issue #230: add support for nii files

---

deepreg/dataset/loader/nifti_loader.py

Reverts DeepRegNet/DeepReg#237
I suggest to revert this PR and do it properly.
We need to
- allow image or label to have suffix either `nii` or `nii.gz`, and their ID do not depend on the suffix
- add test to test these cases
The changes can be
- in `get_sorted_filenames_in_dir`, we will allow a list of suffixes, also rename the func as `get_sorted_filenames_in_dir_with_suffix`
- change `get_data_ids` to make it independent of the file type
To validate the fix,
we need some test data and corresponding tests

Revert "Issue #230: add support for nii files"

---

deepreg/model/layer.py
deepreg/model/layer_util.py
test/unit/test_dataset_load.py
test/unit/test_h5_loader.py
test/unit/test_layer_util.py
test/unit/test_nifti_loader.py
test/unit/test_paired_loader.py
test/unit/test_util.py

use
```
assert "Nifti file path must end with .nii or .nii.gz" in str(exec_info.value)
```
instead of 
```python
msg = " ".join(exec_info.value.args[0].split())
assert "Nifti file path must end with .nii or .nii.gz" in msg
```
also removed `check_inputs` function, as now with tests, this is no longer needed

simplify error message check in tests

---

README.md

Broken links to jupyter notebook due to wrong filename and wrong path to colab.
Fixes #266 
Checked links not broken by clicking from amended README

296 broken edu links

---

docs/Intro_to_Medical_Image_Registration.ipynb

Revert path change in notebook.
Later if we want to update notebook, we should
1. Comment out the switch to tag code in notebook
2. Adapt the notebook to latest master
3. All working, move the tag
4. Push the notebook

Issue #279: revert dir path change [skip ci]

---

README.md
deepreg/dataset/loader/grouped_loader.py
demos/grouped_mask_prostate_longitudinal/README.md
demos/paired_ct_lung/README.md
demos/paired_mrus_brain/README.md
demos/paired_mrus_prostate/README.md
demos/unpaired_ct_lung/README.md
demos/unpaired_mr_brain/README.md
demos/unpaired_us_prostate_cv/README.md
docs/Intro_to_Medical_Image_Registration.ipynb
docs/source/introduction.rst
docs/source/tutorial/custom_loss.md

all the github.io links are updated to readthedocs.io
Fixes #316

Issue #316 github.io links updated to readthedocs

---

demos/unpaired_ct_lung/README.md
demos/unpaired_ct_lung/demo_train.py

unpaired_ct_lung demo uses gpu by default and a note on memory usage has been added to the readme.
Fixes #350

Issue #350: set unpaired_ct_lung to use gpu by default and fix readme

---

deepreg/predict.py
deepreg/train.py
deepreg/util.py
docs/source/docs/cli.md
test/unit/test_predict.py
test/unit/test_train.py
test/unit/test_util.py

Add `log_root` argument for `train` and `predict` functions and corresponding CLI tools so that
logs do not have to be under the root of package.
Fixes #398
apply_

Issue #398: add log_root param to replace hard-coded logs

---

.github/PULL_REQUEST_TEMPLATE.md
.gitignore
CHANGELOG.md
deepreg/model/loss/image.py
deepreg/model/loss/label.py
requirements.txt
test/unit/test_loss_image.py
test/unit/test_loss_label.py

The reason for the bug was related to `tf.math.div_no_nan` which returns 0 when we do division by 0, but the gradient for this might not be well defined and it causes some layers to have non-numeric weights (nan/inf).
Therefore the solution is to add a machine epsilon to both numerator and denominator for the division. Here, instead of defining it manually, we use `tf.keras.backend.epsilon()` which is actually `1e-7` because the machine epsilon for float32 is smaller than 1e-7 but bigger than 1e-8.
```
>>> import numpy as np
>>> np.finfo(np.float32).eps
1.1920929e-07
>>> np.finfo(np.float16).eps
0.000977
```
Fixes #452 
apply_
_Put an `x` in the boxes that apply. You can also fill these out after …

Issue #452: use eps instead of div_no_nan for division

---

docs/source/getting_started/install.rst

Change the ssh protocol to https for better applicability for wider users, in git clone
Fixes #523

using https instead for git clone

---

CHANGELOG.md
deepreg/model/backbone/global_net.py
test/unit/test_backbone.py
test/unit/test_layer_util.py

Fixes #533
Would be better to take the chance to refact global net related tests.
apply_
[change log …

533 wrong bias init in globalnet

---

README.md

Organized badges on README.md
Fixes #540 
apply_
[change log …

Issue #540: Add downloads badge, organize all badges

---

CHANGELOG.md
deepreg/model/layer_util.py
deepreg/warp.py
test/unit/test_layer_util.py
test/unit/test_util.py

Add zero boundary option to resampler, if the location is on the boundary (corners or edges) the values will be zero.
Fixes #615 …

Issue #615: add zero boundary option to resampler and set as default

---

CHANGELOG.md
deepreg/model/network/util.py

Correct typo in the code, which causes not using label loss when image loss is zero.
Fixes #624
e.g. `Issue #<issue number>: …

Issue #624: fix a typo for label loss

---

CHANGELOG.md
deepreg/model/backbone/local_net.py
deepreg/model/backbone/u_net.py
deepreg/model/network.py
test/unit/test_backbone.py
test/unit/test_network.py

Remove BSplines interpolation from being hard-coded in backbones. That will help in:
- When implementing new models, we won't need to add those lines
- It is model-dependent (DVF, DDF) and do no apply for others (e.g., conditional)
Fixes #645 
certain, run `pre-commit …

BSplines interp. independent of the backbone

---

CHANGELOG.md
deepreg/config/parser.py
deepreg/config/v011.py
deepreg/model/network.py
docs/source/docs/configuration.md
test/unit/test_config_v011.py
test/unit/test_network.py

Support the specification of >1 loss functions for each loss type "image", "label", "regularization". I'm not sure it make sense to use multiple loss functions for regularization but anyway it's done.
A config file example is:
```
loss:
"image"
- "name": "ssd"
"weight": 0.5
- "name": "lncc"
"weight": 0.5
"label"
"name": "cross-entropy"
"weight": 1.0
"regularization":
"name": "bending"
"weight": 0.1
...
```
Fixes #526 
[installed …

Multiple loss functions

---

CHANGELOG.md
deepreg/config/parser.py
deepreg/model/network.py
test/unit/test_config_parser.py

As now, `_build_loss` handles the checking and is quite robust. No more need to check losses in sanity checks.
https://github.com/DeepRegNet/DeepReg/blob/main/deepreg/model/network.py#L174
Fixes #613
[our requested …

Issue #613: remove loss weight check in sanity check

---

CHANGELOG.md
deepreg/constant.py
deepreg/dataset/loader/interface.py
deepreg/loss/image.py
deepreg/loss/label.py
deepreg/loss/util.py
deepreg/model/network.py
test/unit/test_interface.py
test/unit/test_loss_label.py
test/unit/test_loss_util.py
test/unit/util.py

Reverts DeepRegNet/DeepReg#719
This PR is buggy.

Revert "690 nan inf loss"

---

CHANGELOG.md
deepreg/constant.py
deepreg/dataset/loader/interface.py
deepreg/loss/image.py
deepreg/loss/label.py
deepreg/loss/util.py
deepreg/model/network.py
examples/custom_image_label_loss.py
examples/custom_parameterized_image_label_loss.py
test/unit/test_interface.py
test/unit/test_loss_image.py
test/unit/test_loss_label.py
test/unit/util.py

change.
Fixes #690
[our requested …

Issue #690: fix negative variance issue and add accurate test
